### ISSUE TITLE
Network delays due to random MAC address use

### ISSUE THREAD

**Issue by mato** [mato/docker-unikernel-runner#1]
Both Mirage/unix and Mirage/Solo5 on ukvm currently use a freshly-generated random (locally administered, unicast) MAC address for each run of the unikernel. If several unikernels are started and stopped _in series_, the Docker-allocated IP address is re-used for each run, but with a _different_ MAC address. If this happens before the host times out its ARP entry for thid IP address then connectivity will be delayed until the ARP entry is updated, potentially causing TCP connections to the unikernel to time out.

Possible solution: Save the container-side `eth0` MAC address, replace it with a randomly-generated one and pass the saved address to the unikernel. May not be 100% reliable due to the "change of address" resulting in DAD or other undesirable communication from the container-side Linux network stack.

**Comment by hannesm** [comment]
see https://github.com/mirage/mirage-tcpip/issues/225

**Comment by mato** [comment]
The Linux sysctl is `net.ipv4.conf.docker0.arp_accept` (assuming the default docker bridge). I've switched the unikernel containers to build against https://github.com/mirage/mirage-dev and have verified with `tcpdump` that the GARP fix from mirage/mirage-tcpip#225 works as expected.

The proper solution is probably still to steal the container-side `eth0` MAC address and use that in the guest, but this helps for now.

**Comment by mato** [comment]
Archiving this repository, closing.
