### ISSUE TITLE
Unable to run unikernel built with unix hypervisor

### ISSUE THREAD

**Issue by vitcozzolino** [mato/docker-unikernel-runner#2]
Hi,
at the moment I'm not able to run my unikernel inside the docker container in unix mode (built and run with unix hypervisor). The error I constantly get when I run `/runtime/runner unix /unikernel/mir-console` is:

`error: execv: not foundernel/mir-console failed: No such file or directory`

After the first try, if I launch the same command again, I receive permanently the following error:
```
No AF_INET address found on veth
error: Unable to determine IP address of eth0
```
After that point, I have to shutdown the docker container and restart it.
Let me add that I have anyway modified the Dockerfile.runner and Dockerfile.runner-build so that the base image I'm using is an ARM debian:jessie (I had problems with the alpine image given that it doesn't run glibc but musl) and the ENTRYPOINT is `/bin/sh`. Technically my unikernel should be good to go considering that all the necessary libraries are located and there are no apparent issues. The followign is the output of `ldd `command:

```
 ldd /unikernel/mir-console
        linux-vdso.so.1 (0x7ef43000)
        libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0x76f29000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76f05000)
        libgmp.so.10 => /lib/libgmp.so.10 (0x76e93000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76e1f000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76e0c000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76d1c000)
        /lib/ld-linux-armhf.so.3 (0x54b04000) 
```

I believe that there is something wrong with the `runner`, given also the inconsistent error message prompted after subsequent executions. But that's just a guess.

**Comment by mato** [comment]
On Thursday, 03.11.2016 at 05:11, Vittorio Cozzolino wrote:

> Hi,
> at the moment I'm not able to run my unikernel inside the docker container in unix mode (built and run with unix hypervisor). The error I constantly get when I run `/runtime/runner unix /unikernel/mir-console` is:
> 
> `error: execv: not foundernel/mir-console failed: No such file or directory`

Is that really the exact error you're getting? If so, I'm not sure where
that's coming from, since the execv() error case in runner.c prints
a different message.

> After the first try, if I launch the same command again, I receive permanently the following error:
> 
> ```
> No AF_INET address found on veth
> error: Unable to determine IP address of eth0
> ```
> 
> After that point, I have to shutdown the docker container and restart it.

That's expected, the network reconfiguration performed by `runner` inside
the container is destructive.

> Let me add that I have anyway modified the Dockerfile.runner and Dockerfile.runner-build so that the base image I'm using is an ARM debian:jessie (I had problems with the alpine image given that it doesn't run glibc but musl) and the ENTRYPOINT is `/bin/sh`. Technically my unikernel should be good to go considering that all the necessary libraries are located and there are no apparent issues. The followign is the output of `ldd`command:
> 
> ```
>  ldd /unikernel/mir-console
>         linux-vdso.so.1 (0x7ef43000)
>         libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0x76f29000)
>         libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76f05000)
>         libgmp.so.10 => /lib/libgmp.so.10 (0x76e93000)
>         libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76e1f000)
>         libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76e0c000)
>         libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76d1c000)
>         /lib/ld-linux-armhf.so.3 (0x54b04000) 
> ```

This looks fine. As you already noticed, the `unix` case is a bit hacky due
to the need for the runner image to share the same base image as the
unikernel binary.

I'm not sure what you're referring to about ENTRYPOINT -- a unix unikernel
should just use `CMD ["/runtime/runner", "unix",
"/unikernel/mir-console"]`. Be sure to use the `[]` form of CMD so that it
doesn't go through `/bin/sh`.

> I believe that there is something wrong with the `runner`, given also the inconsistent error message prompted after subsequent executions. But that's just a guess.

Can you try adding `strace` to your runner image and modifying the
container to launch runner with `strace`? That should tell us more about
why it's failing.

**Comment by vitcozzolino** [comment]
> I'm not sure what you're referring to about ENTRYPOINT -- a unix unikernel
> should just use `CMD ["/runtime/runner", "unix",
> "/unikernel/mir-console"]`. Be sure to use the `[]` form of CMD so that it
> doesn't go through `/bin/sh`.

I just meant that i changed this line `ENTRYPOINT [ "/runtime/runner", "${HYPERVISOR}", "/unikernel/${BIN}" ]`into this `ENTRYPOINT [ "/bin/sh" ]` to access the docker container and then run manually the unikernkel with the runner.

I've attached a txt file containing the strace ->[strace.txt](https://github.com/mato/docker-unikernel-runner/files/569008/strace.txt). 

Mmh, from what I see in the strace output basically it scans for the libraries showed in the output of `ldd`. I suppose all the "`-1 ENOENT (No such file or directory)`" should be ignored as long as he finds at the end the library somewhere. Am I wrong?

What about this last message:

```
write(2, "console: unknown option `--netwo"..., 108console: unknown option `--network'.
Usage: console [OPTION]...
Try `console --help' for more information.
```

Could it be the real issue?

**Comment by mato** [comment]
Oh, right. I didn't realise you were trying to run the `console` example. That won't work, you want something that has a network stack such as `stackv4`. Not sure why you were getting the confusing error message, I don't see that in the strace.

**Comment by vitcozzolino** [comment]
Thank you for the answer. At the moment I'm not able to compile anything with `stackv4`for some kind of issues with opam packages version. Will come back to you when ready.

PS: Actually I'm not running the `console`example, the name is misleading. But anyway you are right, in my original version there is no `stackv4`called.

**Comment by mato** [comment]
Archiving this repository, closing.
