### ISSUE TITLE
Can you run unikernels built with OSv for example?

### ISSUE THREAD

**Issue by radu-matei** [mato/docker-unikernel-runner#5]
Is this unikernel runner built specifically for MirageOS or can it be modified to run OSv unikernels?

Thanks!

**Comment by mato** [comment]
This codebase is indeed specific to MirageOS. I've not tried OSv, however you could almost certainly use the same approach to run OSv unikernels in Docker containers.

I don't have any plans to support unikernels other than MirageOS in _this_ codebase.

**Comment by radu-matei** [comment]
Ok, thanks a lot for your answer.

As I will try to run other unikernels, I might have some questions regarding this codebase.

Thanks!
