### ISSUE TITLE
Configuring tap0 without C binary?

### ISSUE THREAD

**Issue by ansiwen** [mato/docker-unikernel-runner#6]
This is not a real issue but more like a design question. Why do you use a C binary to manage the networking? Last night I was determined to get the tap interface running in the vanilla alpine container without any C binary, just with scripting, and I got it running with this script (no packages required):

```
IP=$(ip -o -f inet address show eth0 | awk '{print $4}')
ip address delete $IP dev eth0
tunctl -t tap0
brctl addbr br0
brctl addif br0 eth0
brctl addif br0 tap0
ifconfig br0 up
ifconfig tap0 up

/my-unikernel --interface tap0 --ipv4 $IP
```
Of course you also have to start the container with `--device=/dev/net/tun:/dev/net/tun --cap-add=NET_ADMIN`.

Is there any disadvantage doing it like that?

Thanks

Sven

**Comment by mato** [comment]
Archiving this repository, closing.
